package com.ruich97.beastlocatorwatch

import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.widget.Button
import android.widget.ImageButton
import android.widget.LinearLayout
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.isVisible
import com.google.android.material.dialog.MaterialAlertDialogBuilder
import org.json.JSONArray
import org.json.JSONObject

class OssLicensesActivity : AppCompatActivity() {
    private lateinit var container: LinearLayout

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_oss_licenses)
        container = findViewById(R.id.ossEntryContainer)

        findViewById<ImageButton>(R.id.ossBackButton).setOnClickListener { finish() }
        renderEntries(loadOssEntries())
    }

    private fun loadOssEntries(): List<OssEntry> {
        return try {
            loadAutoGeneratedEntries()
        } catch (_: Exception) {
            Toast.makeText(this, R.string.oss_auto_load_failed, Toast.LENGTH_SHORT).show()
            emptyList()
        }
    }

    private fun loadAutoGeneratedEntries(): List<OssEntry> {
        val json = assets.open(AUTO_OSS_JSON_ASSET).bufferedReader().use { it.readText() }
        val root = JSONObject(json)
        val items = root.optJSONArray("entries") ?: JSONArray()
        val results = ArrayList<OssEntry>(items.length())
        for (i in 0 until items.length()) {
            val obj = items.optJSONObject(i) ?: continue
            val title = obj.optString("title").ifBlank { obj.optString("coordinate") }
            if (title.isBlank()) continue
            val license = obj.optString("license").ifBlank { getString(R.string.oss_unknown_license) }
            val url = obj.optString("url").ifBlank { null }
            val body = obj.optString("body").ifBlank { null }
            results.add(OssEntry(title = title, license = license, url = url, body = body))
        }
        return results
    }

    private fun renderEntries(entries: List<OssEntry>) {
        container.removeAllViews()
        val inflater = layoutInflater
        entries.forEach { entry ->
            val itemView = inflater.inflate(R.layout.item_oss_license_entry, container, false)
            itemView.findViewById<TextView>(R.id.ossTitle).text = entry.title
            itemView.findViewById<TextView>(R.id.ossLicense).text = entry.license
            val openUrlButton = itemView.findViewById<Button>(R.id.ossOpenUrlButton)
            val showTextButton = itemView.findViewById<Button>(R.id.ossShowTextButton)
            val hasUrl = !entry.url.isNullOrBlank()
            openUrlButton.isEnabled = hasUrl
            openUrlButton.alpha = if (hasUrl) 1f else 0.5f
            openUrlButton.setOnClickListener {
                entry.url?.let(::openUrl)
            }
            val bodyText = resolveBodyText(entry)
            showTextButton.isVisible = bodyText.isNotBlank()
            showTextButton.setOnClickListener {
                MaterialAlertDialogBuilder(this)
                    .setTitle(entry.title)
                    .setMessage(bodyText)
                    .setPositiveButton(android.R.string.ok, null)
                    .show()
            }
            container.addView(itemView)
        }
    }

    private fun resolveBodyText(entry: OssEntry): String {
        if (!entry.body.isNullOrBlank()) return entry.body
        val normalized = entry.license.trim().lowercase()
        return when {
            normalized.contains("apache") && normalized.contains("2.0") ->
                getString(R.string.license_apache_body)
            normalized.contains("odbl") ->
                getString(R.string.license_odbl_body)
            normalized.contains("google play services terms") ->
                getString(R.string.license_google_terms_body)
            else -> entry.url ?: getString(R.string.oss_unknown_url)
        }
    }

    private fun openUrl(url: String) {
        try {
            startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(url)))
        } catch (_: Exception) {
            Toast.makeText(this, R.string.oss_open_failed, Toast.LENGTH_SHORT).show()
        }
    }

    private data class OssEntry(
        val title: String,
        val license: String,
        val url: String?,
        val body: String?
    )

    companion object {
        private const val AUTO_OSS_JSON_ASSET = "oss_licenses/oss_licenses_auto.json"
    }
}

